name: Run flake checks

on:
  push:
    branches:
      - main

jobs:
  checks:
    name: Check Nix flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17
      - name: Run flake checks
        run: nix flake check
